POST  http://localhost:4500/users/register
Content-Type: application/json

{
    "firstName":"May",
    "lastName":"Dean",
    "role":"Specialist",
    "email":"mailing@mailed.com",
    "password":"Passed"  
}

###