POST  http://localhost:4500/users/register
Content-Type: application/json

{
    "firstName":"Sharon",
    "lastName":"Cherotich",
    "role":"Specialist",
    "email":"sharoncherotich112@gmail.com",
    "password":"test12&34"  
}

###